### PR TITLE
Add SingleUniqueNumber Problem

### PR DESCRIPTION
**Pull request by HarshvMahawar**
Please do add Hacktoberfest labels, thanks :)

### CODE REVIEW

**Review by iShayann — CHANGES_REQUESTED** [review]
Please upload folders with problem.md file where you have to mention the problem link and solution.py file with a valid solution that passes all test cases. Do it before 31st night to get hacktoberfest accepted label with merged pr.

**Comment by HarshvMahawar** [comment]
Can I get this merged, and all other prs as well? thanks btw

**Review by iShayann — COMMENTED** [review]
Yeah you will get these merged ... How is your Hacktober Fest progress?

**Comment by HarshvMahawar** [comment]
Yeah, so we have to get 4 PRs merged, and I made only 4 PRs this month and that in on this repo so will have to get all 4 merged to successfully complete Hacktoberfest, so can you please remaining 2 PRs as well, thanks

**Comment by HarshvMahawar** [comment]
You didn't add hacktoberfest labels?

**Pull request merged**
